// flow-typed signature: 748eb5710837b56cf8857520642805cd
// flow-typed version: <<STUB>>/fuzzysearch_v^1.0.3/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fuzzysearch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fuzzysearch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fuzzysearch/test/fuzzysearch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fuzzysearch/index' {
  declare module.exports: $Exports<'fuzzysearch'>;
}
declare module 'fuzzysearch/index.js' {
  declare module.exports: $Exports<'fuzzysearch'>;
}
declare module 'fuzzysearch/test/fuzzysearch.js' {
  declare module.exports: $Exports<'fuzzysearch/test/fuzzysearch'>;
}
