// flow-typed signature: f4aae8a01536a6e7dd1ef910470312cb
// flow-typed version: <<STUB>>/immutable-devtools_v0.0.7/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'immutable-devtools'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'immutable-devtools' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'immutable-devtools/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'immutable-devtools/dist/index.js' {
  declare module.exports: $Exports<'immutable-devtools/dist/index'>;
}
