// flow-typed signature: cb47d324b51f0db2113aeb26d1edaa7b
// flow-typed version: <<STUB>>/imports-loader_v0.8.0/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'imports-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'imports-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'imports-loader/index' {
  declare module.exports: $Exports<'imports-loader'>;
}
declare module 'imports-loader/index.js' {
  declare module.exports: $Exports<'imports-loader'>;
}
