// flow-typed signature: e8dc6b5f0b3f9dc7103ea1b175c9e082
// flow-typed version: <<STUB>>/raw-loader_v^1.0.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'raw-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'raw-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'raw-loader/index' {
  declare module.exports: $Exports<'raw-loader'>;
}
declare module 'raw-loader/index.js' {
  declare module.exports: $Exports<'raw-loader'>;
}
