// flow-typed signature: 973689fd25f7fe477f9a8a76594b7fe0
// flow-typed version: <<STUB>>/webpack-express-middleware_v^1.2.1/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-express-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-express-middleware' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'webpack-express-middleware/index' {
  declare module.exports: $Exports<'webpack-express-middleware'>;
}
declare module 'webpack-express-middleware/index.js' {
  declare module.exports: $Exports<'webpack-express-middleware'>;
}
