// flow-typed signature: 43c68d7d8707a4f10ec5dec3c258e99a
// flow-typed version: <<STUB>>/webpack-express-middleware_v^1.2.1/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-express-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-express-middleware' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'webpack-express-middleware/index' {
  declare module.exports: $Exports<'webpack-express-middleware'>;
}
declare module 'webpack-express-middleware/index.js' {
  declare module.exports: $Exports<'webpack-express-middleware'>;
}
